#!/bin/bash

# create key
# preferably use passkey during setup process
# for everything else, just accept defaults
ssh-keygen -t ed25519 -C "pedroaguilaroficial@gmail.com"

# start ssh-agent in the background
eval "$(ssh-agent -s)"

# create and open ssh config file
touch ~/.ssh/config
nano ~/.ssh/config

# the file content of ~/.ssh/config should be
: '
Host github.com
  AddKeysToAgent yes
  UseKeychain yes
  IdentityFile ~/.ssh/id_ed25519
'

# add passkey to Keychain
ssh-add --apple-use-keychain ~/.ssh/id_ed25519

# add the public key to the clipboard
pbcopy < ~/.ssh/id_ed25519.pub

# paste the public key in github